### ISSUE TITLE
Linux版でxfce環境利用時 ウィンドウの色や透明が反映されない

### ISSUE THREAD

**Issue by nkyossi** [rot1024/jikkyo#20]
Linux LiteやLinux Mint Xfceを使用していた時に、Linuxの64ビット版を使用すると ウィンドウが透明にならなかったり 色の設定が反映されません。
コンポジット処理は有効化済みです。

**Comment by rot1024** [comment]
Linuxでちゃんと動作確認していないので何とも言えないのですが、nw.js v0.13の仕様かなと思います…。
jikkyo v2を最新のElectronで開発し直すことを計画していますので、そこで解決される見通しです。

**Comment by rot1024** [comment]
付属の `jikkyo_ct.sh` を実行するとどうなるか、念のためお知らせ下さい。

**Comment by nkyossi** [comment]
「sh ./jikkyo_ct.sh」を打ってから起動させてみたところ、ウィンドウが透明になりました。
その後、コメントも流れることも確認できました
ありがとうございます。

**Comment by rot1024** [comment]
良かったです。GPUによる描画が無効になるなどデメリットはありますが、とりあえず現状、透明にしたいときは `jikkyo_ct.sh` を実行して下さい :)
