### ISSUE TITLE
OS X向けのリリースファイルの圧縮に問題がある

### ISSUE THREAD

**Issue by mzyy94** [rot1024/jikkyo#5]
https://github.com/rot1024/jikkyo/releases にて公開されている jikkyo-v1.2.0-osx64.zip がOS X標準のアーカイブユーティリティで解凍ができない問題が発生。
また、unzipや7zipでは解凍できるものの、jikkyo.app/Contents/以下のファイルのパーミッションが実行ファイルに適しておらず実行できない状態となっている。

例：実行ファイルのパーミッション

```
 $  ls -l jikkyo.app/Contents/MacOS/nwjs
-rw-r--r--  1 mzyy94  staff  8552 10 16 17:58 jikkyo.app/Contents/MacOS/nwjs
```

環境
- OS X 10.11 El Capitan
- MacBook Air Mid 2013

**Comment by rot1024** [comment]
報告ありがとうございます。
archiverモジュールで圧縮してるのですが、そこらへんに問題があるのでしょうか…。
時間ができ次第、Macにて調査してみます。

**Comment by rot1024** [comment]
OS X El Capitan 10.11 (iMac Late 2013) ・Node.js 5.0.0・npm 3.3.6 にて動作検証を行いました。
- `gulp nw:osx64` でビルドした jikkyo が正常に実行されることを確認しました。
- archiver 0.16.0 で圧縮したzipファイルがアーカイバーユーティリティで正常に解凍でき、正常に起動できることを確認しました。

Windows 7 Home Edition・Node.js 5.0.0・npm 3.3.6・archiver 0.16.0 にてビルド・圧縮したファイルをMacに送りました。
- アーカイバーユーティリティで解凍に成功しましたが、jikkyoの起動に失敗しました。
- 以下の処置を行いましたが、起動できませんでした（何も表示されずにすぐ終了する）。

```
$ ls -l jikkyo.app/Contents/MacOS/nwjs
-rw-rw-rw-@ 1 hoge  staff  8552 11  5 04:31 jikkyo.app/Contents/MacOS/nwjs
$ chmod a+x jikkyo.app/Contents/MacOS/nwjs
$ ls -l jikkyo.app/Contents/MacOS/nwjs
-rwxrwxrwx@ 1 hoge  staff  8552 11  5 04:31 jikkyo.app/Contents/MacOS/nwjs
```

結論としては、
- zipの破損については、archiver@0.15.1の問題か、GitHubへのアップロード時の不具合の可能性
- jikkyoが実行不可能な件は、Windowsでのビルドに問題がある可能性

とりあえず OS X 版は OS X でビルドすることで回避可能という感じですが、根本的な解決方法は調査中です。

**Comment by mzyy94** [comment]
調査どうもです。
こちらでも調査し原因がわかり次第報告します。

**Comment by rot1024** [comment]
今日 v1.2.1 を公開しました。
ひとまずOS Xにてビルドすることで対応しました。
OS X 10.11.1にて、zipファイルが正常に解凍・アプリが起動できることを確認しております。
是非ご確認ください。

**Comment by mzyy94** [comment]
こちらでも問題なく起動できることを確認しました。
Windows上だとパーミッション情報が設定されないという問題も確認できたので、今後はLinuxもしくはOS Xにてビルドすると再発しないかと思われます。
