### ISSUE TITLE
つぶあに設定のディレクトリ選択でキャンセルしてもダイアログが閉じない

### ISSUE THREAD

**Issue by rot1024** [rot1024/jikkyo#7]
つぶあにの保存先設定で、「参照」ボタンからディレクトリ選択ダイアログを開いた状態で、キャンセルボタンをクリックしても、ダイアログが再度開いてしまいます。

Windows 10 Home 64bit

**Comment by rndomhack** [comment]
FileModeのaddEventListenerがinitPreferenceViewに書かれていたため、複数回登録されてしまったことにより起きていました。getPreferenceView側に移動します。
6662e7b0c9f6c8ada736ca8960444428db5e56dc にて修正しました
